### ISSUE TITLE
Exception on `run` and `verify`

### ISSUE THREAD

**Issue by voronianski** [tableflip/nodebot-workshop#21]
Using nodebot-workshop version `2.2.5`, and running the first exercise throws an exception:

```bash
MacBook-Pro-Dmitri:nodebot-workshop dmitri$ nodebot-workshop verify 01-blink-blink.js
module.js:338
    throw err;
          ^
Error: Cannot find module '/usr/local/lib/node_modules/nodebot-workshop/node_modules/johnny-five/node_modules/serialport/build/serialport/v1.7.4/Release/node-v14-darwin-x64/serialport.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Proxyquire._require (/usr/local/lib/node_modules/nodebot-workshop/node_modules/proxyquire/lib/proxyquire.js:158:19)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/nodebot-workshop/node_modules/johnny-five/node_modules/serialport/serialport.js:14:25)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/nodebot-workshop/node_modules/proxyquire/lib/proxyquire.js:237:43)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

Any ideas?

**01-blink-blink.js**

```javascript
var five = require('johnny-five');

var board = new five.Board();
board.on('ready', function () {
    var led = new five.Led(13);
    led.strobe(1000);
});
```

Node version is `0.12.4`, OS X `10.10.3`.

**Comment by olizilla** [comment]
@voronianski try `npm install johnny-five` in the directory that contains your solution.

**Comment by olizilla** [comment]
@voronianski I'm gonna close this issue as it seems inactive. Do let us know if it's still a problem.
